version: '3'


services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3.2.23-alpine
    container_name: clickhouse
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:8123:8123"
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
      - ./logs/clickhouse:/var/log/clickhouse-server/
      - ./config/clickhouse/users.xml:/etc/clickhouse-server/users.xml

  db:
    image: postgres:14
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clickhouse_pq_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    restart: on-failure